resources:
- manuela-ci.yaml
- pipeline.yaml
bases:
- pipeline-resources
- pipelines
#- secrets
- tasks
- configmaps
- github.com/lavlas/manuela-gitops/config/templates/manuela-team-rolebindings
namespace: manuela-ci
