kind: List
apiVersion: v1
items:
- kind: Secret
  apiVersion: v1
  metadata:
    name: quay-build-secret
  data:
    .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJiR3hoYzIxcGRHZ3JiV0Z1ZFdWc1lWOWlkV2xzWkRwUU5VOUdWekJOTUZZM1RVVlRTemhHUWxkTVdVTlNPRFpDVGtWSk5UUXdVRTlSU0ZCVFdWcFJTRnBLTUVsTVRraFpSRUk0TkZjM1NGcFVUa1F3VVV3eCIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
  type: kubernetes.io/dockerconfigjson
