apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: iot-anomaly-detection-pipeline
spec:
  resources:
  - name: gitops-repo
    type: git
  - name: remote-image
    type: image
  - name: git-repo
    type: git
  - name: local-image
    type: image
  tasks:
  - name: build-seldon-image
    taskRef:
      name: s2i-python-3
      kind: ClusterTask
    resources:
      inputs:
        - name: source
          resource: git-repo
      outputs:
        - name: image
          resource: local-image
    params:
      - name: TLSVERIFY
        value: "false"
      - name: PATH_CONTEXT
        value: "."
  - name: bumpversion
    taskRef:
      name: bumpversion
    resources:
      inputs:
        - name: source
          resource: git-repo
    params:
      - name: PATH_CONTEXT
        value: "."
    runAfter:
      - build-seldon-image
  - name: tag-local-image 
    taskRef:
      name: skopeo-tag-image
    resources:
      inputs:
        - name: source
          resource: git-repo
        - name: image
          resource: local-image  
    params:
      - name: PATH_CONTEXT
        value: "."
    runAfter:
      - bumpversion
  - name: modify-gitops-test
    taskRef:
      name: gitops-imagetag
      kind: Task
    runAfter:
      - tag-local-image
    resources:
      inputs:
        - name: source-semver
          resource: git-repo
        - name: source-gitops
          resource: gitops-repo
    params:
    - name: GIT_BRANCH
      value: master
    - name: KUSTOMIZATION_YAML_PATH
      value: config/instances/manuela-tst/kustomization.yaml
    - name: YAML_PATH
      value: images.(name==anomaly-detection).newTag  
    - name: VERSION_PATH
      value: "VERSION"
  - name: argocd-sync-application
    taskRef:
      name: argocd-task-sync-and-wait
    runAfter:
      - modify-gitops-test
    params:
      - name: application-name
        value: manuela-tst-all
      - name: flags
        value: --insecure
      - name: argocd-version
        value: "v1.4.1"
  - name: anomaly-detection-test
    taskRef:
      name: mock
      kind: Task
    runAfter:
      - argocd-sync-application
    params:
      - name: MESSAGE
        value: "succesfully tested model..."
  - name: push-to-quay
    taskRef:
      name: skopeo-copy
      kind: Task
    runAfter:
      - anomaly-detection-test
    resources:
      inputs:
        - name: source
          resource: git-repo
        - name: local-image
          resource: local-image
        - name: remote-image
          resource: remote-image
    params:
    - name: PATH_CONTEXT
      value: components/iot-anomaly-detection
  - name: modify-gitops-prod
    taskRef:
      name: gitops-imagetag
      kind: Task
    runAfter:
      - push-to-quay
    resources:
      inputs:
        - name: source-semver
          resource: git-repo
        - name: source-gitops
          resource: gitops-repo
    params:
    - name: KUSTOMIZATION_YAML_PATH
      value: config/templates/manuela-openshift-prod/anomaly-detection/kustomization.yaml
    - name: YAML_PATH
      value: images.(name==anomaly-detection).newTag  
    - name: GIT_BRANCH
      value: staging-approval
    - name: VERSION_PATH
      value: components/iot-anomaly-detection/VERSION
    - name: IMAGESTREAM_PATH
      value: config/templates/manuela-openshift-prod/anomaly-detection/anomaly-detection-is.yaml 
    - name: REMOTE_IMAGE
      value: quay.io/manuela/iot-anomaly-detection
  - name: create-pull-request
    taskRef:
      name: github-add-pull-request 
    runAfter:
      - modify-gitops-prod
    params:
      - name: GITHUB_REPO
        value: sa-mw-dach/manuela-gitops
      - name: GIT_BRANCH_HEAD
        value: staging-approval
      - name: GIT_BRANCH_BASE
        value: master
